### ISSUE TITLE
TIFSeq.TScluster: Exception in thread "main" java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by LilyLuyang** [czhu/FulQuant#3]
Hi Chen,

Thanks for developing this useful tool!

I encountered some issues when running "bash $SCRIPTDIR/ss_clustering.sh "$outfile".ei.cov.bed.reformatted.tsv &" in the "07_run_clustering.sh" script.
It hints me that the program is encountering a null value where it expects an integer.

The command line in "ss_clustering.sh" shell script is (I just substitute the path into mine):
cd /mypath/FulQuant-master/sw/TScluster
java -cp /mypath/FulQuant-master/sw/TScluster/:jars/* TIFSeq.TScluster F1=$INFILE F2=$CHRLENFILE outF=$OUTFILE HFWINSIZE=5 DISTHRES=8 PTHRESHOLD=3 SUMHOLD=5

There is the error:
[Thu May 09 09:09:39 BST 2024] TIFSeq.TScluster TSFILE=/mypath/combined/all.ei.cov.bed.reformatted.tsv CHRLENFILE=/mypath/FulQuant-master/genome/hg38_SIRV.fa.genomeFile OUTFILE=/mypath/combined/all.ei.cov.bed.reformatted.clustered.bed HFWINSIZE=5 DISTHRES=8 PTHRESHOLD=3 SUMHOLD=5    FORMAT=bed TMP_DIR=/tmp/mypath VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
All transcript sites are read into a linked hashmap...
330
[Thu May 09 09:09:39 BST 2024] TIFSeq.TScluster done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2147483648
Exception in thread "main" java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at TIFSeq.TScluster.clusterChr(TScluster.java:432)
        at TIFSeq.TScluster.doCluster(TScluster.java:153)
        at TIFSeq.TScluster.doWork(TScluster.java:127)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:158)
        at TIFSeq.TScluster.main(TScluster.java:87)

Could you please provide some advice to solve this problem as I have no experience on java troubleshooting.  
I would appreciate it very much!

Best regards,
Lily

**Comment by LilyLuyang** [comment]
> Hi Chen,
> 
> Thanks for developing this useful tool!
> 
> I encountered some issues when running "bash $SCRIPTDIR/ss_clustering.sh "$outfile".ei.cov.bed.reformatted.tsv &" in the "07_run_clustering.sh" script. It hints me that the program is encountering a null value where it expects an integer.
> 
> The command line in "ss_clustering.sh" shell script is (I just substitute the path into mine): cd /mypath/FulQuant-master/sw/TScluster java -cp /mypath/FulQuant-master/sw/TScluster/:jars/* TIFSeq.TScluster F1=$INFILE F2=$CHRLENFILE outF=$OUTFILE HFWINSIZE=5 DISTHRES=8 PTHRESHOLD=3 SUMHOLD=5
> 
> There is the error: [Thu May 09 09:09:39 BST 2024] TIFSeq.TScluster TSFILE=/mypath/combined/all.ei.cov.bed.reformatted.tsv CHRLENFILE=/mypath/FulQuant-master/genome/hg38_SIRV.fa.genomeFile OUTFILE=/mypath/combined/all.ei.cov.bed.reformatted.clustered.bed HFWINSIZE=5 DISTHRES=8 PTHRESHOLD=3 SUMHOLD=5 FORMAT=bed TMP_DIR=/tmp/mypath VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false All transcript sites are read into a linked hashmap... 330 [Thu May 09 09:09:39 BST 2024] TIFSeq.TScluster done. Elapsed time: 0.01 minutes. Runtime.totalMemory()=2147483648 Exception in thread "main" java.lang.NumberFormatException: null at java.base/java.lang.Integer.parseInt(Integer.java:614) at java.base/java.lang.Integer.parseInt(Integer.java:770) at TIFSeq.TScluster.clusterChr(TScluster.java:432) at TIFSeq.TScluster.doCluster(TScluster.java:153) at TIFSeq.TScluster.doWork(TScluster.java:127) at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:158) at TIFSeq.TScluster.main(TScluster.java:87)
> 
> Could you please provide some advice to solve this problem as I have no experience on java troubleshooting. I would appreciate it very much!
> 
> Best regards, Lily

Hi,
I know how to solve this issue. Non-chromosome names in the first column of "all.ei.cov.bed.gz" file should be filtered out as they can nor be recognised by the command lines. Afterwards, only chromosome names, like "chr1", are used for the follwing step to generate "reformatted.tsv".
